version: "3"
services:

  jupyter:
    image: mri.python:latest
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    volumes:
          - "./:/root"
          - "./test:/test" 
          - "./data:/data"
          - "./jupyter:/jupyter"
    environment:
          - JUPYTER_ENABLE_LAB=yes