site_name: dynfc
theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: cyan

repo_url: https://github.com/CoDe-Neuro/dynfc
repo_name: CoDe-Neuro/dynfc

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Installation: installation.md
  - Correlation Methods:
    - cofluct: cofluct-reference.md
    - cc: cc-reference.md
    - corr_slide: corr_slide-reference.md
  - Signal Filtering:
    - butter_design: butter_design-reference.md
    - butter_bandpass_filter: butter_bandpass_filter-reference.md
  - Phase-Locking: 
    - doHilbert: doHilbert-reference.md
    - doKuramoto: doKuramoto-reference.md
    - dPL: dPL-reference.md
    - phDiff: phDiff-reference.md

  - doEuclid: doEuclid-reference.md
  - run_multiPatKOP: run_multiPatKOP-reference.md
  - run_multiPatLEiDA: run_multiPatLEiDA-reference.md
  - get_LEiDA: get_LEiDA-reference.md
  - License: license.md

copyright: Copyright &copy; 2021 Lucas G. S. França and Dafnis Batallé

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CoDe-Neuro
      name: CoDe-Neuro on GitHub