name: docs
on:
  release:
    types: [created]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install mkdocs-material mkdocstrings
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
